[package]
name = "note-mark"
version = "0.0.2"
license = "MIT OR Apache-2.0"
description = "A markdown parser."
readme = "README.md"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peekmore = "1.2.0"
