name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  name: fmt
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - name: Install rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - uses: Swatinem/rust-cache@v2
    - name: Run rustfmt
      run: cargo fmt --all -- --check